### ISSUE TITLE
Please provide source code of "js/planner2.js"

### ISSUE THREAD

**Issue by aik099** [jmalinens/rigas-satiksme-api#1]
The "js/planner2.js" file seems to be compiled from other JS files, because it has 1-3 letter variable names which makes it harder to understand it's logic.

Could you please provide a source (add them to repository) JS files and a build script for regeneration of `planner2.js` file?

**Comment by EchoControl** [comment]
Bump, was trying to understand part of how Name is assigned to "related" stops, failed miserably.

**Comment by jmalinens** [comment]
@EchoControl  @aik099 this was my attempt to  (mostly successfully) reverse engineer rigassatiksme.lv API.
The same planner.js is still available on rigassatiksme.lv homepage:
https://saraksti.rigassatiksme.lv/planner.js?20210629

but when you look at:
https://saraksti.rigassatiksme.lv/riga/routes.txt?1633334400000
https://saraksti.rigassatiksme.lv/riga/stops.txt?1633334400000

After a few years  I stumbled upon some open transit apis and looks like Rīgas Satiksme is using open api and **there is no need to reverse-engineer it!**
(routes.txt has SiriID column)
https://www.transitwiki.org/TransitWiki/index.php/SIRI
 
just find some library which parses this format instead or use GTFS

https://github.com/CUTR-at-USF/awesome-transit


I would also recommend looking at GTFS (General Transit Feed Specification):

https://developers.google.com/transit/gtfs
https://wiki.openstreetmap.org/wiki/General_Transit_Feed_Specification

**Comment by aik099** [comment]
Here is GTFS files for Rigas Satiksme: https://transitfeeds.com/p/rigas-satiksme/333 . However, it doesn't contain a list of express busses (mikroautobusi) since they've splitted into another organization some time ago. It's likely, that they post their GTFS files somewhere as well.
